services:
  jenkins:
    build:
      context: .
      dockerfile: jenkins/Dockerfile
    container_name: jenkins
    restart: unless-stopped
    ports:
      - "8180:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.ssh:/var/jenkins_home/.ssh:rw
    networks:
      - jenkins-net
    secrets:
      - jenkins-secret

networks:
  jenkins-net:
    driver: bridge

volumes:
  jenkins_home:

secrets:
  jenkins-secret:
    file: ./.secrets/jenkins.secret.txt
